apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}-configmap
data:
  zookeeper-config.properties: |
    zooMyId=1
    zooLogDir=/store/logs
    zooDataLogDir=/store/datalog
    zooPort=2181
    zooDataDir=/store/data
