apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-{{ .Values.serviceEnsemble.name }}
  labels:
{{ include "zookeeper.labels" . | indent 4 }}
spec:
  clusterIP: {{ .Values.serviceEnsemble.clusterIP }}
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
{{ include "zookeeper.labels" . | indent 4 }}
spec:
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
