apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "zookeeper.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zookeeper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Values.serviceEnsemble.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zookeeper.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: 
        - "/bin/sh"
        - "-c"
        - "if [ ! -d $ZOO_DATA_DIR ] ; then mkdir -p $ZOO_DATA_DIR ; chmod 777 $ZOO_DATA_DIR ; else touch /conf/test; fi && \
           if [ ! -d $ZOO_LOG_DIR ] ; then mkdir -p $ZOO_LOG_DIR ; chmod 777 $ZOO_LOG_DIR ; else touch /conf/test; fi && \
           if [ ! -d $ZOO_DATA_LOG_DIR ] ; then mkdir -p $ZOO_DATA_LOG_DIR ; chmod 777 $ZOO_DATA_LOG_DIR ; else touch /conf/test; fi && \
           if [ ! -f $ZOO_DATA_DIR/myid ] ; then $(echo $((${HOSTNAME##*-}+1)) > $ZOO_DATA_DIR/myid ) else touch /conf/test; fi && \
           /docker-entrypoint.sh zkServer.sh start-foreground"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: vol
          mountPath: /store
        ports:
        - name: zkport
          containerPort: {{ .Values.service.port }}
        - name: zkportpeers
          containerPort: 2888
        - name: zkportelection
          containerPort: 3888
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ZOO_LOG_DIR
            valueFrom:
              configMapKeyRef:
                name: {{ include "zookeeper.fullname" . }}-config
                key: zooLogDir
          - name: ZOO_DATA_DIR
            valueFrom:
              configMapKeyRef:
                name: {{ include "zookeeper.fullname" . }}-config
                key: zooDataDir
          - name: ZOO_DATA_LOG_DIR
            valueFrom:
              configMapKeyRef:
                name: {{ include "zookeeper.fullname" . }}-config
                key: zooDataLogDir
  volumeClaimTemplates:
  - metadata:
      name: vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 32Gi
